services:
  - type: web
    name: springboot-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    #port: 8080
    envVars:		
      - key: MONGODB_URI	  	
        value: mongodb+srv://javainfohari_db_user:ATHQc3eHM8Oye0ys@cluster0.z2ilog6.mongodb.net/dailyExpense?ssl=true&replicaSet=atlas-kt3s9d-shard-0&authSource=admin&retryWrites=true&w=majority
	

	