# App name
spring.application.name=TransactionsToMongo
spring.profiles.active=prod

# MongoDB
#spring.mongodb.uri=${MONGODB_URI}

# Server
server.port=${PORT:8080}

# Thymeleaf (keep defaults, just confirming)
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false


spring.mongodb.uri=mongodb+srv://javainfohari_db_user:ATHQc3eHM8Oye0ys@cluster0.z2ilog6.mongodb.net/dailyExpense?ssl=true&replicaSet=atlas-kt3s9d-shard-0&authSource=admin&retryWrites=true&w=majority
spring.mongodb.database=dailyExpense
spring.mongodb.username=javainfohari_db_user
spring.mongodb.password=ATHQc3eHM8Oye0ys
spring.mongodb.port=27017
spring.mongodb.ssl.enabled=true

#server.port=8080
