# App name
spring.application.name=TransactionsToMongo
spring.profiles.active=prod

# MongoDB
spring.mongodb.uri=${MONGODB_URI}

# Server
server.port=${PORT:8080}

# Thymeleaf (keep defaults, just confirming)
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false


#spring.mongodb.uri=mongodb+srv://javainfohari_db_user:ATHQc3eHM8Oye0ys@cluster0.z2ilog6.mongodb.net/dailyExpense
#spring.mongodb.database=dailyExpense
#server.port=8080
